services:

  db:
    image: postgres
    command: ["postgres", "-c", "wal_level=logical"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  walstream:
    build: .
    command: ["start", "publication", "replication_slot"]
    ports:
      - 50051:50051
    environment:
      CONNECTION: postgresql://postgres:postgres@db/postgres
    depends_on:
      db:
        condition: service_healthy
        restart: true